
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "5276bb1aee3f75c73c26cd4777ae1a426b1342ab",
 "version": "v0.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
